### ISSUE TITLE
Example cloud-init script

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-infra/jupyter-deploy#1]
The following is an example cloud init script that I got working with Jupyter, ngrok, and traefik:

```
#cloud-config

# Bootstrap
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ubuntu-drivers-common

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /opt/docker/compose.yaml
    owner: root:root
    permissions: '0644'
    content: |
      services:
        traefik:
          image: traefik:v2.10
          command:
            - "--api=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--log.level=DEBUG"
          ports:
            - "127.0.0.1:80:80"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
          networks:
            - web

        jupyter:
          image: quay.io/jupyter/base-notebook:latest
          networks:
            - web
          environment:
            - JUPYTER_TOKEN=ABC
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jupyter.rule=HostRegexp(`{any:.*}`)"
            - "traefik.http.routers.jupyter.entrypoints=web"
            - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
          volumes:
            - /home/ubuntu:/home/jovyan

        ngrok:
          image: ngrok/ngrok:latest
          command:
            - "http"
            - "traefik:80"  # Points to traefik service
            - "--oauth"
            - "google"
            - "--oauth-allow-email"
            - "ellisonbg@gmail.com,zachsailer@gmail.com"
          environment:
            - NGROK_AUTHTOKEN=<key goes here>
          networks:
            - web

      networks:
        web:
          driver: bridge

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  # Install Docker and Docker Compose
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - apt-get install -y docker-compose-plugin
  - systemctl start docker
  - systemctl enable docker
  - cd /opt/docker
  - docker compose up -d


```
